# Generated by Django 4.2.21 on 2025-06-01 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.CharField(choices=[('HM', 'Headless Mami'), ('HQ', 'Holy Quintet'), ('WPS', 'Walpurgisnacht Section'), ('KMS', 'Kyubey Monitoring Squad')], max_length=10)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Contact number must be in the format: 0912 345 6789', regex='^09\\d{2} \\d{3} \\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('quiz_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('activity_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('exam_weight', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('grading_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('activity', 'Activity'), ('quiz', 'Quiz'), ('exam', 'Exam')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('max_score', models.FloatField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'grade_type', 'title'), name='unique_grade_per_student'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_enrollment'),
        ),
    ]
